name: Setup Emscripten toolchain
description: ⚡ Install and configure Emscripten for GitHub Actions

branding:
  icon: play
  color: green

inputs:
  emsdk-version:
    default: latest
  emsdk-token:
    default: ${{ github.server_url == 'https://github.com' && github.token || '' }}
  cache:
    default: true

  # Backwards compatibility
  # version: {}
  # no-install: {}
  # no-cache: {}
  # cache-key: {}

outputs:
  emsdk-version: {}
  cache-hit: {}

runs:
  using: node20
  main: dist/main.js
  post: dist/post.js
